# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 793)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(483, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/icon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.contacts_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.contacts_scrollArea.setWidgetResizable(True)
        self.contacts_scrollArea.setObjectName("contacts_scrollArea")
        self.contacts_scrollAreaW = QtWidgets.QWidget()
        self.contacts_scrollAreaW.setGeometry(QtCore.QRect(0, 0, 463, 597))
        self.contacts_scrollAreaW.setObjectName("contacts_scrollAreaW")
        self.contacts_layout = QtWidgets.QVBoxLayout(self.contacts_scrollAreaW)
        self.contacts_layout.setObjectName("contacts_layout")
        self.contact0_label = QtWidgets.QLabel(self.contacts_scrollAreaW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contact0_label.sizePolicy().hasHeightForWidth())
        self.contact0_label.setSizePolicy(sizePolicy)
        self.contact0_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.contact0_label.setObjectName("contact0_label")
        self.contacts_layout.addWidget(self.contact0_label)
        self.line = QtWidgets.QFrame(self.contacts_scrollAreaW)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.contacts_layout.addWidget(self.line)
        self.pushButton = QtWidgets.QPushButton(self.contacts_scrollAreaW)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setCheckable(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.contacts_layout.addWidget(self.pushButton)
        self.contacts_scrollArea.setWidget(self.contacts_scrollAreaW)
        self.gridLayout.addWidget(self.contacts_scrollArea, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newContact_pb = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./img/addContact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newContact_pb.setIcon(icon1)
        self.newContact_pb.setIconSize(QtCore.QSize(16, 16))
        self.newContact_pb.setObjectName("newContact_pb")
        self.gridLayout_2.addWidget(self.newContact_pb, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.gridLayout_2, 7, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.tags_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.tags_combo_box.setObjectName("tags_combo_box")
        self.tags_combo_box.addItem("")
        self.tags_combo_box.setItemText(0, "")
        self.gridLayout_3.addWidget(self.tags_combo_box, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.search_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line_edit.setClearButtonEnabled(True)
        self.search_line_edit.setObjectName("search_line_edit")
        self.gridLayout_3.addWidget(self.search_line_edit, 3, 1, 1, 1)
        self.sort_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.sort_combobox.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.sort_combobox.setObjectName("sort_combobox")
        self.sort_combobox.addItem("")
        self.sort_combobox.addItem("")
        self.gridLayout_3.addWidget(self.sort_combobox, 1, 2, 1, 1)
        self.tags_filter_label = QtWidgets.QLabel(self.centralwidget)
        self.tags_filter_label.setObjectName("tags_filter_label")
        self.gridLayout_3.addWidget(self.tags_filter_label, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.search_pb = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("search")
        self.search_pb.setIcon(icon)
        self.search_pb.setObjectName("search_pb")
        self.gridLayout_3.addWidget(self.search_pb, 3, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact Manager"))
        self.contact0_label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.newContact_pb.setText(_translate("MainWindow", "New contact"))
        self.label.setText(_translate("MainWindow", "Sort by:"))
        self.search_line_edit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.sort_combobox.setCurrentText(_translate("MainWindow", "Name"))
        self.sort_combobox.setItemText(0, _translate("MainWindow", "Name"))
        self.sort_combobox.setItemText(1, _translate("MainWindow", "Surname"))
        self.tags_filter_label.setText(_translate("MainWindow", "Filter  tag:"))
        self.search_pb.setText(_translate("MainWindow", "..."))

